#!/bin/bash

wget -O anaPla.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Anas_platyrhynchos/RNA/rna.gbk.gz
wget -O aptFor.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Aptenodytes_forsteri/RNA/rna.gbk.gz
wget -O aquChr.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Aquila_chrysaetos_canadensis/RNA/rna.gbk.gz
wget -O calAnn.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Calypte_anna/RNA/rna.gbk.gz
wget -O chaPel.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Chaetura_pelagica/RNA/rna.gbk.gz
wget -O chaVoc.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Charadrius_vociferus/RNA/rna.gbk.gz
wget -O colLiv.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Columba_livia/ARCHIVE/ANNOTATION_RELEASE.100/RNA/rna.gbk.gz
wget -O corBra.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Corvus_brachyrhynchos/RNA/rna.gbk.gz
wget -O cucCan.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Cuculus_canorus/RNA/rna.gbk.gz
wget -O egrGar.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Egretta_garzetta/RNA/rna.gbk.gz
wget -O falPer.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Falco_peregrinus/ARCHIVE/ANNOTATION_RELEASE.100/RNA/rna.gbk.gz
wget -O ficAlb.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Ficedula_albicollis/RNA/rna.gbk.gz
wget -O galGal.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000002315.3_Gallus_gallus-4.0/GCF_000002315.3_Gallus_gallus-4.0_rna.gbff.gz
wget -O geoFor.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Geospiza_fortis/ARCHIVE/ANNOTATION_RELEASE.100/RNA/rna.gbk.gz
wget -O halLeu.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Haliaeetus_leucocephalus/RNA/rna.gbk.gz
wget -O melGal.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Meleagris_gallopavo/RNA/rna.gbk.gz
wget -O melUnd.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Melopsittacus_undulatus/ARCHIVE/ANNOTATION_RELEASE.100/RNA/rna.gbk.gz
wget -O nipNip.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Nipponia_nippon/RNA/rna.gbk.gz
wget -O picPub.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Picoides_pubescens/RNA/rna.gbk.gz
wget -O pseHum.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Pseudopodoces_humilis/ARCHIVE/ANNOTATION_RELEASE.100/RNA/rna.gbk.gz
wget -O pygAde.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Pygoscelis_adeliae/RNA/rna.gbk.gz
wget -O serCan.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Serinus_canaria/RNA/rna.gbk.gz
wget -O strCam.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Struthio_camelus_australis/RNA/rna.gbk.gz
wget -O taeGut.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Taeniopygia_guttata/RNA/rna.gbk.gz
wget -O tinGut.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Tinamus_guttatus/RNA/rna.gbk.gz
wget -O balReg.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Balearica_regulorum_gibbericeps/RNA/rna.gbk.gz
wget -O fulGla.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Fulmarus_glacialis/RNA/rna.gbk.gz
wget -O lepDis.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Leptosomus_discolor/RNA/rna.gbk.gz
wget -O mesUni.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Mesitornis_unicolor/RNA/rna.gbk.gz
wget -O allMis.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Alligator_mississippiensis/ARCHIVE/ANNOTATION_RELEASE.100/RNA/rna.gbk.gz
wget -O anoCar.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Anolis_carolinensis/RNA/rna.gbk.gz
wget -O chrPic.rna.gbk.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Chrysemys_picta/RNA/rna.gbk.gz
