## TESTS FOR RATITE-SPECIFIC ACCELERATION, ETC ##

#for each chicken-ratite pair, get the alignability including duplicates for that pair (should be 0, 1, 2+)
#run in alignDepths subdir
for $SP in droNov casCas aptHaa aptOwe aptRow rheAme rhePen strCam
do
	halAlignmentDepth --inMemory --countDupes --noAncestors --targetGenomes $SP ~/ratite_scratch/wga/ratite_final_20150627/ratiteAlign.hal galGal > galGal-$SP.align.wig &
done

#everything below is run in the accelTests subdir

#setup:
#make galGal chrom list for downstream processing
cut -f1,1 ../galGal.chromsizes | sort -u > chr.list

#get beds
cp ../ce_beds/final_ces_noratite.tree2.bed.gz final_noratite_tree2.bed.gz
cp ../ce_beds/final_ces.tree2.bed.gz final_all_tree2.bed.gz
gunzip *.bed.gz

#general procedure for acceleration tests:
#goal is to do three things:
#1) run standard phyloP to get test of acceleration for each ratite branch, all ratite branches together, and the tinamou clade
#2) run standard phyloP with the same set of branches but on a set of 5e6 random alignments generated by msa_view
#--the tricky part here is matching the length distribution
#3) run phyloP with SPH option to estimate posterior distribution of sites?

#1:
mkdir -p ratite tips clades tinamou
NEUTMOD="$HOME/ratite_scratch/phast/neutMods/neut_ver2_final.named.mod"
for CHR in $(cat chr.list)
do
	ALIGN="../final_mafs/$CHR.final.maf"
	if [[ -f $ALIGN ]]
	then
		grep "^$CHR" $BED > $CHR.temp.bed
		sbatch est_accel.sh $NEUTMOD $CHR $ALIGN
	fi
done

#2:
#first need to make fake alignments
for CHR in $(cat chr.list)
do
	ALIGN="../final_mafs/$CHR.final.maf"
	if [[ -f $ALIGN ]]
	then
		

#concatenate output
for CHR in $(cat chr.list)
do
	cat emu_out/${CHR}* | grep "^$CHR" >> emu_accel_prelim.out
done

#sort
sort -k1,1 -k2,2n -k3,3n -k4,4 -u emu_accel_prelim.out > emu_accel_sorted.out


#things still to do: calculate conservation in ratite-only alignments
#merge up everything
#null models and tinamou tests
#specific ratite branches

##OLD CODE BELOW

#replace 0s in pval column with 1e-05 or -1e-05
perl -p -i -e 's/0.00000$/0.00001/' ratite_accel.final.out
perl -p -i -e 's/0.00000$/0.00001/' tinamou_accel.final.out

##generate a null model with 10 random samples of lineages
for i in 1 2 3 4 5 6 7 8 9 10
do
	brinput=$(nw_labels named_tree.nh | grep -v "anoCar" | chooseLines -k 13 - | tr '\n' ',')
	echo $brinput > rand$i.branches
	sbatch est_accel_rand.sh $i $brinput
done

#concatenate output
for CHR in $(tail -n +2 galGal4.chr2acc | cut -f2,2)
do
	for i in 1 2 3 4 5 6 7 8 9 10
	do
		cat rand$i/$CHR* | grep "^$CHR" >> rand${i}_accel.final.out
	done
done

#replace 0s
for FILE in $(ls rand*.out); do perl -p -i -e 's/0.00000$/0.00001/' $FILE; done