wget -O anaPla.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Anas_platyrhynchos/GFF/ref_BGI_duck_1.0_top_level.gff3.gz
wget -O aptFor.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Aptenodytes_forsteri/GFF/ref_ASM69914v1_top_level.gff3.gz
wget -O aquChr.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Aquila_chrysaetos_canadensis/GFF/ref_Aquila_chrysaetos-1.0.2_top_level.gff3.gz
wget -O calAnn.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Calypte_anna/GFF/ref_ASM69908v1_top_level.gff3.gz
wget -O chaPel.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Chaetura_pelagica/GFF/ref_ChaPel_1.0_top_level.gff3.gz
wget -O chaVoc.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Charadrius_vociferus/GFF/ref_ASM70802v2_top_level.gff3.gz
wget -O colLiv.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Columba_livia/ARCHIVE/ANNOTATION_RELEASE.100/GFF/ref_Cliv_1.0_top_level.gff3.gz
wget -O corBra.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Corvus_brachyrhynchos/GFF/ref_ASM69197v1_top_level.gff3.gz
wget -O cucCan.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Cuculus_canorus/GFF/ref_ASM70932v1_top_level.gff3.gz
wget -O egrGar.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Egretta_garzetta/GFF/ref_ASM68718v1_top_level.gff3.gz
wget -O falPer.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Falco_peregrinus/ARCHIVE/ANNOTATION_RELEASE.100/GFF/ref_F_peregrinus_v1.0_top_level.gff3.gz
wget -O ficAlb.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Ficedula_albicollis/GFF/ref_FicAlb1.5_top_level.gff3.gz
wget -O galGal.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Gallus_gallus/GFF/ref_Gallus_gallus-4.0_top_level.gff3.gz
wget -O geoFor.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Geospiza_fortis/ARCHIVE/ANNOTATION_RELEASE.100/GFF/ref_GeoFor_1.0_top_level.gff3.gz
wget -O halLeu.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Haliaeetus_leucocephalus/GFF/ref_Haliaeetus_leucocephalus-4.0_top_level.gff3.gz
wget -O melGal.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Meleagris_gallopavo/GFF/ref_Turkey_5.0_top_level.gff3.gz
wget -O melUnd.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Melopsittacus_undulatus/ARCHIVE/ANNOTATION_RELEASE.100/GFF/ref_Melopsittacus_undulatus_6.3_top_level.gff3.gz
wget -O nipNip.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Nipponia_nippon/GFF/ref_ASM70822v1_top_level.gff3.gz
wget -O picPub.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Picoides_pubescens/GFF/ref_ASM69900v1_top_level.gff3.gz
wget -O pseHum.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Pseudopodoces_humilis/ARCHIVE/ANNOTATION_RELEASE.100/GFF/ref_PseHum1.0_top_level.gff3.gz
wget -O pygAde.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Pygoscelis_adeliae/GFF/ref_ASM69910v1_top_level.gff3.gz
wget -O serCan.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Serinus_canaria/GFF/ref_SCA1_top_level.gff3.gz
wget -O strCam.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Struthio_camelus_australis/GFF/ref_ASM69896v1_top_level.gff3.gz
wget -O taeGut.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Taeniopygia_guttata/GFF/ref_Taeniopygia_guttata-3.2.4_top_level.gff3.gz
wget -O tinGut.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Tinamus_guttatus/GFF/ref_ASM70537v2_top_level.gff3.gz
wget -O balReg.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Balearica_regulorum_gibbericeps/GFF/ref_ASM70989v1_top_level.gff3.gz
wget -O fulGla.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Fulmarus_glacialis/GFF/ref_ASM69083v1_top_level.gff3.gz
wget -O lepDis.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Leptosomus_discolor/GFF/ref_ASM69178v1_top_level.gff3.gz
wget -O mesUni.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Mesitornis_unicolor/GFF/ref_ASM69576v1_top_level.gff3.gz
wget -O allMis.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Alligator_mississippiensis/ARCHIVE/ANNOTATION_RELEASE.100/GFF/ref_allMis0.2_top_level.gff3.gz
wget -O anoCar.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Anolis_carolinensis/GFF/ref_AnoCar2.0_top_level.gff3.gz
wget -O chrPic.gff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Chrysemys_picta/GFF/ref_Chrysemys_picta_bellii-3.0.3_top_level.gff3.gz

gunzip *.gff.gz
