wget -O anaPla.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Anas_platyrhynchos/protein/protein.fa.gz
wget -O aptFor.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Aptenodytes_forsteri/protein/protein.fa.gz
wget -O aquChr.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Aquila_chrysaetos_canadensis/protein/protein.fa.gz
wget -O calAnn.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Calypte_anna/protein/protein.fa.gz
wget -O chaPel.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Chaetura_pelagica/protein/protein.fa.gz
wget -O chaVoc.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Charadrius_vociferus/protein/protein.fa.gz
wget -O colLiv.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Columba_livia/ARCHIVE/ANNOTATION_RELEASE.100/protein/protein.fa.gz
wget -O corBra.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Corvus_brachyrhynchos/protein/protein.fa.gz
wget -O cucCan.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Cuculus_canorus/protein/protein.fa.gz
wget -O egrGar.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Egretta_garzetta/protein/protein.fa.gz
wget -O falPer.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Falco_peregrinus/ARCHIVE/ANNOTATION_RELEASE.100/protein/protein.fa.gz
wget -O ficAlb.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Ficedula_albicollis/protein/protein.fa.gz
wget -O galGal.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Gallus_gallus/protein/protein.fa.gz
wget -O geoFor.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Geospiza_fortis/ARCHIVE/ANNOTATION_RELEASE.100/protein/protein.fa.gz
wget -O halLeu.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Haliaeetus_leucocephalus/protein/protein.fa.gz
wget -O melGal.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Meleagris_gallopavo/protein/protein.fa.gz
wget -O melUnd.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Melopsittacus_undulatus/ARCHIVE/ANNOTATION_RELEASE.100/protein/protein.fa.gz
wget -O nipNip.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Nipponia_nippon/protein/protein.fa.gz
wget -O picPub.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Picoides_pubescens/protein/protein.fa.gz
wget -O pseHum.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Pseudopodoces_humilis/ARCHIVE/ANNOTATION_RELEASE.100/protein/protein.fa.gz
wget -O pygAde.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Pygoscelis_adeliae/protein/protein.fa.gz
wget -O serCan.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Serinus_canaria/protein/protein.fa.gz
wget -O strCam.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Struthio_camelus_australis/protein/protein.fa.gz
wget -O taeGut.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Taeniopygia_guttata/protein/protein.fa.gz
wget -O tinGut.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Tinamus_guttatus/protein/protein.fa.gz
wget -O balReg.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Balearica_regulorum_gibbericeps/protein/protein.fa.gz
wget -O fulGla.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Fulmarus_glacialis/protein/protein.fa.gz
wget -O lepDis.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Leptosomus_discolor/protein/protein.fa.gz
wget -O mesUni.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Mesitornis_unicolor/protein/protein.fa.gz
wget -O allMis.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Alligator_mississippiensis/ARCHIVE/ANNOTATION_RELEASE.100/protein/protein.fa.gz
wget -O anoCar.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Anolis_carolinensis/protein/protein.fa.gz
wget -O chrPic.fa.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/Chrysemys_picta/protein/protein.fa.gz

gunzip *.fa.gz
