for file in /n/edwards_lab/Users/tsackton/ratites/annotation/gff/*.genome.gff; do base=${file##*/}; species=${base%%.*}; awk 'BEGIN{OFS="\t";} {if ($3 ~ /gene/) print $1, $4-1, $5, $9, ".", $7}' $file > $species.gene.bed; done
for file in /n/edwards_lab/Users/tsackton/ratites/assembly/ASSEMBLY_FREEZE/*.fa.gz; do base=${file##*/}; species=${base%%.*}; gzip -cd $file > $species.fa; samtools faidx $species.fa; done
for file in *.gene.bed; do species=${file%%.*};  bedtools flank -i $species.gene.bed -l 2000 -r 0 -s -g $species.fa.fai > $species.2kbupstream.bed; done
for file in *.2kbupstream.bed; do species=${file%%.*}; bedtools subtract -a $file -b $species.gene.bed -s > $species.promoter.bed; done
for file in *.promoter.bed; do species=${file%%.*}; bedtools getfasta -fi $species.fa -bed $file -name -s > $species.promoter.fa; done

#PSPM from https://www.ncbi.nlm.nih.gov/pubmed/20304998


−7	−6	−5	−4	−3	−2	−1	0	1	2	3	4	5	6	7
A	77	0	80	100	0	73	12	23	31	42	4	38	38	12	27
C	0	0	0	0	100	4	15	39	15	19	11	12	8	73	27
G	19	100	8	0	0	0	42	19	23	4	77	0	31	0	4
T	4	0	12	0	0	23	31	19	31	35	8	50	23	15	42


#converting to MEME format

MEME version 4
ALPHABET= ACGT

MOTIF ARE

letter-probability matrix:
0.77	0	0.19	0.04
0	0	1	0
0.8	0	0.08	0.12
1	0	0	0
0	1	0	0
0.73	0.04	0	0.23
0.12	0.15	0.42	0.31
0.23	0.39	0.19	0.19
0.31	0.15	0.23	0.31
0.42	0.19	0.04	0.35
0.04	0.11	0.77	0.08
0.38	0.12	0	0.50
0.38	0.08	0.31	0.23
0.12	0.73	0	0.15
0.27	0.27	0.04	0.42

#now run fimo
for file in *.promoter.fa; do species=${file%%.*}; fimo --o ${species}_fimo_out --oc ${species}_fimo_out ARE.motif $file &> $species.fimo.log & done

